#!/bin/bash

# Get the Function App URI from azd environment
echo "🔍 Getting Azure Function App URL from azd environment..."

# Check if azd is installed
if ! command -v azd &> /dev/null; then
    echo "❌ Error: Azure Developer CLI (azd) is not installed"
    echo "Please install it from: https://learn.microsoft.com/azure/developer/azure-developer-cli/install-azd"
    exit 1
fi

# Get the Function URI from azd
FUNCTION_URI=$(azd env get-values | grep AZURE_FUNCTION_URI | cut -d '=' -f 2 | tr -d '"')

if [ -z "$FUNCTION_URI" ]; then
    echo "❌ Error: Could not get AZURE_FUNCTION_URI from azd environment"
    echo "Make sure you've run 'azd up' first"
    exit 1
fi

# Remove trailing slash if present
FUNCTION_URI=${FUNCTION_URI%/}

echo "✅ Found Function App URL: $FUNCTION_URI"

# Create .env.local file
ENV_FILE="src/web/.env.local"

echo "📝 Creating $ENV_FILE..."

cat > "$ENV_FILE" << EOF
# Azure Functions API URL (auto-generated by setup-env.sh)
# Last updated: $(date)
NEXT_PUBLIC_API_URL=$FUNCTION_URI
EOF

echo "✅ Environment file created successfully!"
echo ""
echo "📄 Contents of $ENV_FILE:"
cat "$ENV_FILE"
echo ""
echo "🚀 You can now run 'cd src/web && npm run dev' to start the development server"
